project:
  type: website

website:
  title: "ISSS608-coursework website"
  navbar:
    left: 
      - text: "Hands-on Exercise"
        menu: 
        - text: "Hands-on Exercise 1"
          href: "HE01.html"
        - text: "Hands-on Exercise 2"
          href: "HE02.html"
        - text: "Hands-on Exercise 3"
          href: "HE03.html"
      - text: "In-class Exercise"
        menu:
        - text: "In-class Exercise 1"
          href: "IE01.html"
    right:
      - about.qmd

format:
  html:
    theme:
      - Lumen
      - brand
    css: styles.css
    toc: true

editor: visual

